export const masterConfig = {
    kantor: {
        title: 'Kantor',
        endpoint: '/master/kantor',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'tipe', label: 'Tipe', badge: true },
            { key: 'alamat', label: 'Alamat' },
            { key: 'radius', label: 'Radius (m)' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'id_entitas', label: 'Entitas', type: 'select', endpoint: '/organisasi/entitas?per_page=200', optionLabel: 'nama', optionValue: 'id', required: true },
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'tipe', label: 'Tipe', type: 'select', options: ['pusat', 'cabang', 'kas'], required: true },
            { key: 'alamat', label: 'Alamat', type: 'textarea' },
            { key: 'telepon', label: 'Telepon', type: 'text' },
            { key: 'latitude', label: 'Latitude', type: 'number', step: '0.0000001', required: true },
            { key: 'longitude', label: 'Longitude', type: 'number', step: '0.0000001', required: true },
            { key: 'radius', label: 'Radius (meter)', type: 'number', required: true },
            { key: 'zona_waktu', label: 'Zona Waktu', type: 'text' },
        ],
    },
    'unit-kerja': {
        title: 'Unit Kerja',
        endpoint: '/master/unit-kerja',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'kantor.nama', label: 'Kantor' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'id_kantor', label: 'Kantor', type: 'select', endpoint: '/master/kantor?per_page=200', optionLabel: 'nama', optionValue: 'id', required: true },
            { key: 'id_departemen', label: 'Departemen', type: 'select', endpoint: '/organisasi/departemen?per_page=200', optionLabel: 'nama', optionValue: 'id' },
        ],
    },
    jabatan: {
        title: 'Jabatan',
        endpoint: '/master/jabatan',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'level', label: 'Level' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'level', label: 'Level', type: 'number', required: true },
            { key: 'bisa_approve', label: 'Bisa Approve', type: 'checkbox' },
        ],
    },
    jadwal: {
        title: 'Jadwal Kerja',
        endpoint: '/master/jadwal',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'jam_masuk', label: 'Jam Masuk' },
            { key: 'jam_pulang', label: 'Jam Pulang' },
            { key: 'toleransi_terlambat_menit', label: 'Toleransi (mnt)' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'jam_masuk', label: 'Jam Masuk', type: 'time', required: true },
            { key: 'jam_pulang', label: 'Jam Pulang', type: 'time', required: true },
            { key: 'toleransi_terlambat_menit', label: 'Toleransi Terlambat (menit)', type: 'number' },
            { key: 'toleransi_pulang_awal_menit', label: 'Toleransi Pulang Awal (menit)', type: 'number' },
            { key: 'is_default', label: 'Jadwal Default', type: 'checkbox' },
        ],
    },
    'hari-libur': {
        title: 'Hari Libur',
        endpoint: '/master/hari-libur',
        columns: [
            { key: 'tanggal', label: 'Tanggal' },
            { key: 'nama', label: 'Nama' },
            { key: 'jenis', label: 'Jenis', badge: true },
            { key: 'tahun', label: 'Tahun' },
        ],
        fields: [
            { key: 'tanggal', label: 'Tanggal', type: 'date', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'jenis', label: 'Jenis', type: 'select', options: ['nasional', 'perusahaan', 'kantor'], required: true },
            { key: 'id_kantor', label: 'Kantor (kosongkan = semua)', type: 'select', endpoint: '/master/kantor?per_page=200', optionLabel: 'nama', optionValue: 'id' },
            { key: 'tahun', label: 'Tahun', type: 'number', required: true },
        ],
        hasStatus: false,
    },
    'jenis-izin': {
        title: 'Jenis Izin/Cuti',
        endpoint: '/master/jenis-izin',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'kategori', label: 'Kategori', badge: true },
            { key: 'durasi_default_hari', label: 'Durasi Default' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'kategori', label: 'Kategori', type: 'select', options: ['izin', 'cuti_tahunan', 'block_leave', 'cuti_melahirkan', 'cuti_besar'], required: true },
            { key: 'durasi_default_hari', label: 'Durasi Default (hari)', type: 'number' },
            { key: 'is_potong_cuti', label: 'Potong Cuti', type: 'checkbox' },
            { key: 'dokumen_wajib', label: 'Dokumen Wajib', type: 'checkbox' },
            { key: 'max_hari_per_tahun', label: 'Max Hari/Tahun', type: 'number' },
            { key: 'sla_jam', label: 'SLA (jam)', type: 'number' },
        ],
    },
    'jenis-pengumuman': {
        title: 'Jenis Pengumuman',
        endpoint: '/master/jenis-pengumuman',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'perlu_approval', label: 'Perlu Approval', badge: true },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'perlu_approval', label: 'Perlu Approval', type: 'checkbox' },
        ],
    },
    'komponen-gaji': {
        title: 'Komponen Gaji',
        endpoint: '/master/komponen-gaji',
        columns: [
            { key: 'kode', label: 'Kode' },
            { key: 'nama', label: 'Nama' },
            { key: 'tipe', label: 'Tipe', badge: true },
            { key: 'urutan', label: 'Urutan' },
            { key: 'status', label: 'Status', badge: true },
        ],
        fields: [
            { key: 'kode', label: 'Kode', type: 'text', required: true },
            { key: 'nama', label: 'Nama', type: 'text', required: true },
            { key: 'tipe', label: 'Tipe', type: 'select', options: ['pendapatan', 'potongan'], required: true },
            { key: 'urutan', label: 'Urutan', type: 'number' },
        ],
    },
};
